name = "Nostal's Optimization Pack"
author = "NostalFinals"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e41f393c5efa9bc3f12556c23e282a9737b18c2a5bfed7620ff335084a31871"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.25"
